language: php

php:
  - '7.2'
  - '7.3'
  - '7.4'
  - '8.0'

before_script:
  - composer install -n

script:
  - phpunit --coverage-clover=coverage.xml --configuration=phpunit.xml

after_script:
 - bash <(curl -s https://codecov.io/bash)